# Generated by Django 5.2.3 on 2025-06-27 15:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('Student', 'Student'), ('Farmer', 'Farmer'), ('Entrepreneur', 'Entrepreneur'), ('Other', 'Other')], max_length=20)),
                ('background', models.TextField(help_text='Brief background information')),
                ('project_title', models.CharField(max_length=255)),
                ('project_description', models.TextField()),
                ('estimated_budget', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('funding_needed', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('location', models.CharField(max_length=255)),
                ('project_document', models.FileField(blank=True, null=True, upload_to='kyc/documents/projects/')),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes for verification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_kyc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farmer KYC',
                'verbose_name_plural': 'Farmer KYCs',
            },
        ),
        migrations.CreateModel(
            name='InvestorKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('id_type', models.CharField(choices=[('passport', 'Passport'), ('national_id', 'National ID'), ('driver_license', "Driver's License")], max_length=20)),
                ('id_number', models.CharField(max_length=100)),
                ('id_document', models.FileField(blank=True, null=True, upload_to='kyc/documents/id/')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='kyc/profiles/')),
                ('address', models.TextField()),
                ('occupation', models.CharField(max_length=200)),
                ('income_source', models.CharField(choices=[('salary', 'Salary'), ('business', 'Business'), ('investment', 'Investment'), ('other', 'Other')], max_length=20)),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('purpose', models.TextField(help_text='Purpose of the investment account')),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes for verification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_kyc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investor KYC',
                'verbose_name_plural': 'Investor KYCs',
            },
        ),
        migrations.CreateModel(
            name='KYCVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending Review'), ('updated', 'Updated')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_actions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC Verification Log',
                'verbose_name_plural': 'KYC Verification Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
