# Generated by Django 5.2.3 on 2025-07-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerkyc',
            name='changes_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investorkyc',
            name='changes_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
