# Generated by Django 5.2.3 on 2025-07-14 08:48

import backend.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_investorkyc_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.AlterField(
            model_name='farmerkyc',
            name='id_document',
            field=models.FileField(storage=backend.storage_backends.MediaStorage(), upload_to='documents/id/'),
        ),
        migrations.AlterField(
            model_name='farmerkyc',
            name='profile_picture',
            field=models.ImageField(storage=backend.storage_backends.MediaStorage(), upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='investorkyc',
            name='id_document',
            field=models.FileField(storage=backend.storage_backends.MediaStorage(), upload_to='documents/id/'),
        ),
        migrations.AlterField(
            model_name='investorkyc',
            name='profile_picture',
            field=models.ImageField(storage=backend.storage_backends.MediaStorage(), upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('funded', 'Funded'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
    ]
