# Generated by Django 5.2.3 on 2025-06-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_farmerkyc_investorkyc_kycverificationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycverificationlog',
            name='action',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending Review'), ('updated', 'Updated'), ('change_requested', 'Change Requested')], max_length=20),
        ),
    ]
