# Generated by Django 5.2.3 on 2025-07-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_mymodel_alter_farmerkyc_id_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('funded', 'Funded'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
