# Generated by Django 5.2.3 on 2025-06-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_otptoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otptoken',
            options={'ordering': ['-otp_created_at']},
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
