# Generated by Django 5.2.3 on 2025-06-30 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerkyc',
            name='estimated_budget',
        ),
        migrations.RemoveField(
            model_name='farmerkyc',
            name='funding_needed',
        ),
        migrations.RemoveField(
            model_name='farmerkyc',
            name='location',
        ),
        migrations.RemoveField(
            model_name='farmerkyc',
            name='project_description',
        ),
        migrations.RemoveField(
            model_name='farmerkyc',
            name='project_document',
        ),
        migrations.RemoveField(
            model_name='farmerkyc',
            name='project_title',
        ),
        migrations.AddField(
            model_name='farmerkyc',
            name='address',
            field=models.TextField(default='', help_text='Complete address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerkyc',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerkyc',
            name='id_document',
            field=models.FileField(default='', upload_to='documents/id/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerkyc',
            name='id_number',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerkyc',
            name='id_type',
            field=models.CharField(choices=[('National ID', 'National ID'), ('Passport', 'Passport'), ("Driver's License", "Driver's License"), ('Voter ID', 'Voter ID')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerkyc',
            name='nationality',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerkyc',
            name='profile_picture',
            field=models.ImageField(default='', upload_to='profiles/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investorkyc',
            name='id_document',
            field=models.FileField(default='', upload_to='documents/id/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investorkyc',
            name='notes',
            field=models.TextField(help_text='Admin notes for verification'),
        ),
        migrations.AlterField(
            model_name='investorkyc',
            name='profile_picture',
            field=models.ImageField(default='', upload_to='profiles/'),
            preserve_default=False,
        ),
    ]
