# Generated by Django 5.2.3 on 2025-06-30 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_remove_farmerkyc_estimated_budget_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerkyc',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='investorkyc',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='kycverificationlog',
            name='notes',
        ),
    ]
