# Generated by Django 5.2.3 on 2025-07-02 23:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_remove_farmerkyc_notes_remove_investorkyc_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('team', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('grant', 'Grant'), ('hackathon', 'Hackathon'), ('funding_mentorship', 'Funding + Mentorship'), ('competition', 'Competition'), ('accelerator', 'Accelerator'), ('other', 'Other')], max_length=50)),
                ('tags', models.JSONField(default=list, help_text='List of tags')),
                ('description', models.TextField()),
                ('full_description', models.TextField()),
                ('amount', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
                ('application_link', models.URLField(help_text='Link to application form or website', max_length=500)),
                ('posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('views', models.PositiveIntegerField(default=0)),
                ('applicants', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Opportunities',
                'ordering': ['-posted'],
            },
        ),
    ]
