# Generated by Django 5.2.3 on 2025-07-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_opportunity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='team',
            new_name='theme',
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='type',
            field=models.CharField(choices=[('grant', 'Grant'), ('hackathon', 'Hackathon'), ('funding_mentorship', 'Funding + Mentorship'), ('competition', 'Competition'), ('other', 'Other')], max_length=50),
        ),
    ]
