name: capstone
region: kigali
services:
- name: capstone-project
  github:
    branch: main
    deploy_on_push: true
  dockerfile_path: Dockerfile
  http_port: 8080
  health_check:
    http_path: /
    initial_delay_seconds: 10
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  envs:
  - key: NODE_ENV
    value: production